server:
  port: 8887
  servlet:
    context-path: /market-auth
spring:
  datasource:
    url: jdbc:h2:file:./users;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jooq:
    sql-dialect:


jwt:
  secret: ag%$45wqag$%asdf@4!q1F$qefw1asdfFFFEaFa23af4t5Gstdretfq2gsdfg$fafda
  lifetime: 36000000
